### PR TITLE
Add Log textbox. Add basic UI for network monitoring.

### PR DESCRIPTION
**Pull request by runapp**
Add Log textbox. Add basic UI for network monitoring. Make KeyboardHookLL hooks on demand.

### CODE REVIEW

**Comment by zokker13** [comment]
Looks pretty cool, thanks!
Do you want to add something more or can I merge this?

**Comment by runapp** [comment]
Err.. I'm not sure. Actually I have no more ideas at this time.

**Comment by zokker13** [comment]
Ideas about UI and logging or something different? If it's the latter, we can just make another PR.

**Comment by runapp** [comment]
Yup. :-)

**Comment by zokker13** [comment]
Okay. :D
Looking forward to it. 👍

**Pull request closed without merging**
